=== NCEAS/morpho/lib/catalog/eml-file.dtd
<!--
  * Ecological Metadata Language (EML) - Data set structural descriptors
  *
  *      Authors: Matt Jones, Zheng Wang, and Noah Goldstein
  * Organization: National Center for Ecological Analysis and Synthesis
  *  For Details: http://www.nceas.ucsb.edu/
  *      Created: 1997 August 19
  *     Modified: 1999 June 23
  *      Version: 1.4
  *    File Info: '$Id: eml-file.dtd,v 1.1 2000-07-12 19:47:20 higgins Exp $'
  *
  * Ecological Metadata Language is a general purpose metadata content
  * specification for documenting ecological data.  The specification 
  * consists of a series of modular document type definitions (DTD) that 
  * provide metadata content descriptors. It describes the owner and  
  * contents of the dataset  (eml-dataset.dtd), the research context in 
  * which it was created (eml-context.dtd), the structural 
  * characteristics of data files (eml-file.dtd), the 
  * characteristics of variables in a file (eml-variable.dtd), current 
  * status of data and metadata files (eml-status.dtd), access control 
  * rules regarding the data  and metadata (eml-access.dtd), software 
  * information (eml-software) and a variety of miscellaneous 
  * supplemental descriptors (eml-supplement.dtd).
  * 
  * Files generated under the structural constraints of eml are
  * plain-text files and therefore are editable in ordinary
  * text-processors.  However, these DTDs are intended for use within 
  * general purpose metadata editors, and within a more specific 
  * metadata editor being developed at NCEAS for the ecological 
  * community.  This metadata editor will provide facilities for 
  * version control and efficient metadata entry.  
  * The purpose of this specification was to formalize the 
  * Michener et al. work in a structured language to examine its 
  * application to ecological data in a controlled manner.
  *
  * This specification was based on the work of the Ecological Society 
  * of America's Committee on the Future of Long Term Data, and more
  * specifically on a related paper, Michener et al., 1997. See:
  * Michener, William K., et al., 1997. Ecological Appications,
  * "Nongeospatial metadata for the ecological sciences"
  * Vol 7(1). pp. 330-342.
  *
  * Where appropriate, we have used elements of the ISO/TC 211 draft 
  * standard - the ISO Geographic information/Geomatics standard, 
  * which includes xml code, as well as ISO 8601 schema. Some elements 
  * in the ISO/TC 211 were expanded to allow for greater 
  * resolution.
  *
  * For an explanation of the classes of metadata and elements defined 
  * below, see Michener et al. 1997. In particular, the numbered comment 
  * labels found below refer to Table 1 (pp. 336-337) of Michener 
  * et al. 1997. In addition, each of the principal elements in the 
  * specification is accompanied by a FIXED attribute called "description"
  * that provides a brief description of the content of the element. These
  * descriptions are derived from Michener et al. 1997.
  *
-->

<!--    *      *      *      *
        CLASS IV - DATA STRUCTURE DESCRIPTORS
        *      *      *      *
        -->

<!-- Class 4 -->
<!ELEMENT eml-file (meta_file_id, file)>
<!ATTLIST eml-file description CDATA #FIXED "Data structural descriptors">
<!ELEMENT meta_file_id (#PCDATA)>
<!ATTLIST meta_file_id description CDATA #FIXED "Unique identifier of this metadata record">

<!-- Class 4.A -->
<!ELEMENT file (file_name, file_size?, format, orientation?, header_lines?,
                case_sensitive?, geographic_coverage*, temporal_coverage*,
                authentication*, data_problem*)>
<!ATTLIST file description CDATA #FIXED "Data set file">

<!-- Class 4.A.1 -->
<!ELEMENT file_name (#PCDATA) >
<!ATTLIST file_name description CDATA #FIXED "File name">

<!-- Class 4.A.2 -->
<!ELEMENT file_size (amount, unit) >
<!ATTLIST file_size description CDATA #FIXED "Size of file">
<!ELEMENT amount (#PCDATA) >
<!ATTLIST amount description CDATA #FIXED "Amount">
<!ELEMENT unit (#PCDATA) >
<!ATTLIST unit description CDATA #FIXED "Unit">


<!-- Class 4.A.3 -->
<!ELEMENT format (compressed|encoded|base_file_type)>
<!ATTLIST format description CDATA #FIXED "File type and compression schemes employed">
<!ELEMENT compressed (#PCDATA)>
<!ATTLIST compressed description CDATA #FIXED "Method of compression">
<!ELEMENT encoded (#PCDATA)>
<!ATTLIST encoded description CDATA #FIXED "Method of encoding">
<!ELEMENT base_file_type (ASCII|binary)>
<!ATTLIST base_file_type description CDATA #FIXED "Base file type">
<!ELEMENT ASCII (record_delimiter)>
<!ATTLIST ASCII description CDATA #FIXED "ASCII">
<!ELEMENT record_delimiter (#PCDATA)>
<!ATTLIST record_delimiter description CDATA #FIXED "Record delimiter">
<!ELEMENT binary EMPTY>
<!ATTLIST binary description CDATA #FIXED "Binary">

<!-- NEW SECTION -->
<!ELEMENT orientation EMPTY >
<!ATTLIST orientation columnorrow (columnmajor|rowmajor) "columnmajor"
		      description CDATA #FIXED "Is file column major or row major?">

<!-- Class 4.A.4 -->
<!ELEMENT header_lines (#PCDATA) >
<!ATTLIST header_lines description CDATA #FIXED "Number of header lines or information that prepares data">

<!-- Class 4.A.5 -->
<!ELEMENT case_sensitive EMPTY >
<!ATTLIST case_sensitive yesorno (y|n) "n"
                   description CDATA #FIXED "Case sensitivity of field">
 
<!-- Class 4.A.6 -->
<!-- the field "specialfield" was removed as there were questions to its usefull ness -->

<!ELEMENT geographic_coverage (paragraph*, coordinates*)>
<!ATTLIST geographic_coverage description CDATA #FIXED "Geographic coverage">

<!ELEMENT coordinates (lattitude, longitude) >
<!ATTLIST coordinates description CDATA #FIXED "Cartesian Coordinates">
<!ELEMENT lattitude (#PCDATA)>
<!ATTLIST lattitude direction (north|south) #REQUIRED
                    description CDATA #FIXED "Lattitude coordinates">
<!ELEMENT longitude (#PCDATA)>
<!ATTLIST longitude direction (east|west) #REQUIRED
                    description CDATA #FIXED "Longitude coordinates">

<!ELEMENT temporal_coverage (start_date,stop_date?)>
<!ATTLIST temporal_coverage description CDATA #FIXED "Temporal coverage">
<!ELEMENT start_date (datetime)>
<!ATTLIST start_date description CDATA #FIXED "Date data collection commenced">
<!ELEMENT datetime (year?, month?, day?, hour?, minute?, second?, second_fraction?, time_zone_designator?)>
<!ATTLIST datetime description CDATA #FIXED "Date and time as designated in ISO 8601">
<!ELEMENT year (#PCDATA)>
<!ATTLIST year description CDATA #FIXED "Year in YYYY format">
<!ELEMENT month (#PCDATA)>
<!ATTLIST month description CDATA #FIXED "Month in MM format">
<!ELEMENT day (#PCDATA)>
<!ATTLIST day description CDATA #FIXED "Day of month in DD format">
<!ELEMENT hour (#PCDATA)>
<!ATTLIST hour description CDATA #FIXED "Hour in hh">
<!ELEMENT minute (#PCDATA)>
<!ATTLIST minute description CDATA #FIXED "Minute in mm">
<!ELEMENT second (#PCDATA)>
<!ATTLIST second description CDATA #FIXED "Seconds in ss">
<!ELEMENT second_fraction (#PCDATA)>
<!ATTLIST second_fraction description CDATA #FIXED "One or more digits representing a decimal fraction of a second">
<!ELEMENT time_zone_designator (#PCDATA)>
<!ATTLIST time_zone_designator description CDATA #FIXED "Time zone designator">

<!ELEMENT stop_date  (datetime)>
<!ATTLIST stop_date description CDATA #FIXED "Date data collection terminated">


<!-- Class 4.A.7 -->
<!ELEMENT authentication (#PCDATA) >
<!ATTLIST authentication description CDATA #FIXED "Authentication procedures or techniques">


<!-- Class 4.B -->
<!-- Class 4.B (variable) was moved to its own module (eml-variable.dtd) -->

<!-- Class 4.C -->
<!ELEMENT data_problem (paragraph+)>
<!ATTLIST data_problem problemtype (missing|anomaly|error) #REQUIRED
                      description CDATA #FIXED "Data anomalies; description of missing data">
<!ELEMENT paragraph (#PCDATA)>
<!ATTLIST paragraph description CDATA #FIXED "Paragraph of text">

<!-- End of file -->

=== NCEAS/morpho/lib/file_template.xml
<?xml version="1.0"?>
<!DOCTYPE eml-file PUBLIC "-//NCEAS//eml-file//EN" "file:///PROGRAM FILES/MORPHO/catalog/eml-file.dtd" >
<eml-file description="Data structural descriptors">
<meta_file_id description="Unique identifier of this metadata record">
 </meta_file_id>
<file description="Data set file">
<file_name description="File name">build.xml</file_name>
<file_size description="Size of file">
<amount description="Amount">
 </amount>
<unit description="Unit">
 </unit>
</file_size>
<format description="File type and compression schemes employed">
<compressed description="Method of compression">
 </compressed>
 <ASCII description="ASCII">
<record_delimiter description="Record delimiter">
 </record_delimiter>
</ASCII>
<Empty >
</Empty>
</format>
<orientation columnorrow="(columnmajor,rowmajor)columnmajor"  description="Is file column major or row major?">
<Empty >
</Empty>
</orientation>
<header_lines description="Number of header lines or information that prepares data">
 </header_lines>
<case_sensitive description="Case sensitivity of field"  yesorno="(y,n)n">
<Empty >
</Empty>
</case_sensitive>
<geographic_coverage description="Geographic coverage">
<paragraph description="Paragraph of  ">
 </paragraph>
<coordinates description="Cartesian Coordinates">
<lattitude direction="(north,south)"  description="Lattitude coordinates">
 </lattitude>
<longitude direction="(east,west)"  description="Longitude coordinates">
 </longitude>
</coordinates>
</geographic_coverage>
<temporal_coverage description="Temporal coverage">
<start_date description="Date data collection commenced">
<datetime description="Date and time as designated in ISO 8601">
<year description="Year in YYYY format">
 </year>
<month description="Month in MM format">
 </month>
<day description="Day of month in DD format">
 </day>
<hour description="Hour in hh">
 </hour>
<minute description="Minute in mm">
 </minute>
<second description="Seconds in ss">
 </second>
<second_fraction description="One or more digits representing a decimal fraction of a second">
 </second_fraction>
<time_zone_designator description="Time zone designator">
 </time_zone_designator>
</datetime>
</start_date>
<stop_date description="Date data collection terminated">
<datetime description="Date and time as designated in ISO 8601">
<year description="Year in YYYY format">
 </year>
<month description="Month in MM format">
 </month>
<day description="Day of month in DD format">
 </day>
<hour description="Hour in hh">
 </hour>
<minute description="Minute in mm">
 </minute>
<second description="Seconds in ss">
 </second>
<second_fraction description="One or more digits representing a decimal fraction of a second">
 </second_fraction>
<time_zone_designator description="Time zone designator">
 </time_zone_designator>
</datetime>
</stop_date>
</temporal_coverage>
<authentication description="Authentication procedures or techniques">
 </authentication>
<data_problem problemtype="(missing,anomaly,error)"  description="Data anomalies; description of missing data">
<paragraph description="Paragraph of  ">
 </paragraph>
</data_problem>
</file>
</eml-file>
