=== NCEAS/morpho/lib/catalog/eml-dataset-2.0.dtd
<!--         
       '$RCSfile: eml-dataset-2.0.dtd,v $'
       Copyright: 2000 Regents of the University of California and the
                  National Center for Ecological Analysis and Synthesis
     For Details: http://knb.ecoinformatics.org/

        '$Author: jones $'
          '$Date: 2001-05-23 06:32:11 $'
      '$Revision: 1.1 $'

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
-->

<!ENTITY % responsibleParty "((individualName|organizationName|positionName)+,
                             address*, phone*, electronicMailAddress*, 
                             onlineLink*, role+)">

<!ELEMENT individualName (salutation*, givenName*, surName)>
<!ELEMENT salutation (#PCDATA)>
<!ELEMENT givenName (#PCDATA)>
<!ELEMENT surName (#PCDATA)>

<!ELEMENT organizationName (#PCDATA)>
<!ELEMENT positionName (#PCDATA)>

<!ELEMENT address (deliveryPoint*, city?, administrativeArea?, 
                   postalCode?, country?)>
<!ELEMENT deliveryPoint (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT administrativeArea (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone phonetype CDATA "voice">
<!ELEMENT electronicMailAddress (#PCDATA)>
<!ELEMENT onlineLink (#PCDATA)>

<!-- Note that the domain for role is not expressed in the DTD -->
<!ELEMENT role (#PCDATA)>


<!-- entity to conglomerate these fields into one name -->
<!ENTITY % resbase "(identifier+, shortName?, title+,
                     originator+, pubDate?, pubPlace?, series?, abstract?, 
                     keywordSet*, additionalInfo?, triple*)" >

<!-- common fields -->
<!ELEMENT identifier (#PCDATA)>
<!ATTLIST identifier system CDATA "">
<!ELEMENT shortName (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT originator ((%responsibleParty;))>
<!ELEMENT pubdate (#PCDATA)>
<!ELEMENT pubplace (#PCDATA)>
<!ELEMENT series (#PCDATA)>
<!ELEMENT abstract (paragraph+)>
<!ELEMENT keywordSet (keyword+, keywordThesaurus*)>
<!ELEMENT keyword (#PCDATA)>
<!ATTLIST keyword keywordType CDATA "">
<!ELEMENT keywordThesaurus (#PCDATA)>
<!ELEMENT additionalInfo (paragraph+)>
<!ELEMENT paragraph (#PCDATA)>
<!ELEMENT triple (subject, relationship, object)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT relationship (#PCDATA)>
<!ELEMENT object (#PCDATA)>


<!ELEMENT temporalCoverage (#PCDATA)>
<!ELEMENT geographicCoverage (#PCDATA)>
<!ELEMENT taxonomicCoverage (#PCDATA)>


<!-- The dataset branch -->
<!ELEMENT dataset ((%resbase;), temporalCoverage*, geographicCoverage*,
                  taxonomicCoverage* )>

<!-- EOF -->

=== NCEAS/morpho/lib/dataset.xml
<?xml version="1.0"?>
<!DOCTYPE dataset PUBLIC "-//NCEAS//eml-dataset-2.0//EN" "file:////C:/work/dmanclient/lib/catalog/eml-dataset-2.0.dtd">

<dataset editor="edu.ucsb.nceas.morpho.editor.LockedPanel" help="The container for fields describing a dataset resource.">
  <identifier  help="The unique identifier of this metadata file or object."></identifier>
  <shortName help="A short name that describes the resource, sometimes a filename."></shortName>
  <title help="A brief description of the resource, providing enough detail to differentiate it from other similar resources."></title>
  <originator help="The 'originator' element provides the full name of the person, organization, or position associated with the resource.">
      <individualName help="The full name of the person being described">
        <salutation>text</salutation>
        <givenName>text</givenName>
        <surName>berkley</surName>
      </individualName>
    <address help="The full address information for a given responsible party entry.">
      <deliveryPoint help="The delivery point field is used for the physical address for postal communication."></deliveryPoint>
      <city help="The city field is used for the city name of the contact associated with a particular resource."></city>
      <administrativeArea></administrativeArea>
      <postalCode></postalCode>
      <country>USA</country>
    </address>
    <phone phonetype="voice"></phone>
    <electronicMailAddress>text</electronicMailAddress>
    <onlineLink></onlineLink>
    <role>originator</role>
  </originator>
  <pubdate>text</pubdate>
  <pubplace>text</pubplace>
  <series>text</series>
  <abstract>
    <paragraph>text</paragraph>
  </abstract>
  <keywordSet>
    <keyword help="keyword" keywordType=""></keyword>
    <keywordThesaurus></keywordThesaurus>
  </keywordSet>
  <additionalInfo>
    <paragraph>text</paragraph>
  </additionalInfo>
  <triple>
    <subject></subject>
    <relationship></relationship>
    <object></object>
  </triple>
</dataset>
