=== NCEAS/morpho/lib/imsvdex_v1p0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	IPR, License and Distribution Notices
	This machine readable file is derived from IMS specification IMS Vocabulary Definition Exchange XML Binding Version 1.0 Final Specification    
	found at http://www.imsglobal.org/vdex/ and the original IMS schema binding or code base 
	http://www.imsglobal.org/vdex/vdexv1p0/imsvdex_bindv1p0.html.
	
	Recipients of this document are requested to submit, with their comments, notification of any relevant patent 
	claims or other intellectual property rights of which they may be aware that might be infringed by the schema 
	binding contained in this document.
	
	IMS takes no position regarding the validity or scope of any intellectual property or other rights that might be 
	claimed to pertain to the implementation or use of the technology described in this document or the extent to 
	which any license under such rights might or might not be available; neither does it represent that it has made 
	any effort to identify any such rights. Information on IMS’s procedures with respect to rights in IMS specifications 
	can be found at the IMS Intellectual Property Rights web page: http://www.imsglobal.org/ipr/imsipr_policyFinal.pdf.
	
	Copyright © IMS Global Learning Consortium 1999-2007. All Rights Reserved.
	
	License Notice for Users
	Users of products or services that include this document are hereby granted a worldwide, royalty-free, 
	non-exclusive license to use this document.
	
	Distribution Notice for Developers
	Developers of products or services that provide distribution of this document as is or with modifications are 
	required to register with the IMS community on the IMS website as described in the following two paragraphs:
	
	- If you wish to distribute this document as is, with no modifications, you are hereby granted permission to copy, 
	display and distribute the contents of this document in any medium for any purpose without fee or royalty provided 
	that you include this IPR, License and Distribution notice in its entirety on ALL copies, or portions thereof, that you 
	make and you complete a valid license registration with IMS and receive an email from IMS granting the license. 
	To register, follow the instructions on the IMS website: http://www.imsglobal.org/specificationdownload.cfm. Once 
	registered you are granted permission to transfer unlimited distribution rights of this document for the purposes 
	of third-party or other distribution of your product or service that incorporates this document as long as this IPR, 
	License and Distribution notice remains in place in its entirety.
	
	- If you wish to create and distribute a derived work from this document, you are hereby granted permission to copy, 
	display and distribute the contents of the derived work in any medium for any purpose without fee or royalty provided 
	that you include this IPR, License and Distribution notice in its entirety on ALL copies, or portions thereof, that you 
	make and you complete a valid profile registration with IMS and receive an email from IMS granting the license. To 
	register, follow the instructions on the IMS website: http://www.imsglobal.org/profile/. Once registered you are 
	granted permission to transfer unlimited distribution rights of the derived work for the purposes of third-party or 
	other distribution of your product or service that incorporates the derived work as long as this IPR, License and 
	Distribution notice remains in place in its entirety.
	
	The limited permissions granted above are perpetual and will not be revoked by IMS or its successors or assigns.
	
	THIS SPECIFICATION IS BEING OFFERED WITHOUT ANY WARRANTY WHATSOEVER, AND IN PARTICULAR, 
	ANY WARRANTY OF NONINFRINGEMENT IS EXPRESSLY DISCLAIMED. ANY USE OF THIS SPECIFICATION 
	SHALL BE MADE ENTIRELY AT THE IMPLEMENTER’S OWN RISK, AND NEITHER THE CONSORTIUM, NOR 
	ANY OF ITS MEMBERS OR SUBMITTERS, SHALL HAVE ANY LIABILITY WHATSOEVER TO ANY IMPLEMENTER 
	OR THIRD PARTY FOR ANY DAMAGES OF ANY NATURE WHATSOEVER, DIRECTLY OR INDIRECTLY, ARISING 
	FROM THE USE OF THIS SPECIFICATION.
-->
<!--Generated by Turbo XML 2.3.1.100. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xs:schema targetNamespace="http://www.imsglobal.org/xsd/imsvdex_v1p0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.imsglobal.org/xsd/imsvdex_v1p0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:element name="vdex" type="vdexType" block="#all"/>
	<xs:element name="metadata" type="metadataType" block="#all"/>
	<xs:element name="langstring" type="langstringType" block="#all"/>
	<xs:element name="caption" type="langstringBag" block="#all"/>
	<xs:element name="description" type="descriptionType" block="#all"/>
	<xs:element name="term" type="termType" block="#all"/>
	<xs:element name="relationship" type="relationshipType" block="#all"/>
	<xs:element name="mediaDescriptor" type="mediaDescriptorType" block="#all"/>
	<xs:element name="mediaLocator" type="mediaLocatorType" block="#all"/>
	<xs:element name="targetTerm" type="termRefType" block="#all"/>
	<xs:element name="sourceTerm" type="termRefType" block="#all"/>
	<xs:complexType name="identifierType">
		<xs:simpleContent>
			<xs:extension base="xs:anyURI">
				<xs:anyAttribute namespace="##other" processContents="lax"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="mediaLocatorType">
		<xs:simpleContent>
			<xs:extension base="xs:anyURI">
				<xs:anyAttribute namespace="##other" processContents="lax"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="mediaDescriptorType">
		<xs:sequence>
			<xs:element ref="mediaLocator"/>
			<xs:element name="interpretationNote" type="descriptionType" block="#all" minOccurs="0"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="relationshipType">
		<xs:sequence>
			<xs:element name="relationshipIdentifier" type="identifierType" block="#all" minOccurs="0"/>
			<xs:element ref="sourceTerm"/>
			<xs:element ref="targetTerm"/>
			<xs:element name="relationshipType" type="vocabType" block="#all" minOccurs="0"/>
			<xs:element ref="metadata" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="termType">
		<xs:sequence>
			<xs:element name="termIdentifier" type="identifierType" block="#all"/>
			<xs:element ref="caption" minOccurs="0"/>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="mediaDescriptor" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="metadata" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="term" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="orderSignificant" type="xs:boolean" default="false"/>
		<xs:attribute name="validIndex" type="xs:boolean" default="true"/>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="metadataType">
		<xs:sequence>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="vdexType">
		<xs:sequence>
			<xs:element name="vocabName" type="langstringBag" block="#all" minOccurs="0"/>
			<xs:element name="vocabIdentifier" type="vocabIdentifierType" block="#all" minOccurs="0"/>
			<xs:element ref="term" maxOccurs="unbounded"/>
			<xs:element ref="relationship" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="metadata" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="orderSignificant" type="xs:boolean" default="false"/>
		<xs:attribute name="profileType" type="vdexProfilesType" default="lax"/>
		<xs:attribute name="language" type="xs:language"/>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="langstringType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="xs:language"/>
				<xs:anyAttribute namespace="##other" processContents="lax"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="langstringBag">
		<xs:sequence>
			<xs:element ref="langstring" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="vocabType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI" use="required"/>
				<xs:anyAttribute namespace="##other" processContents="lax"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="descriptionType">
		<xs:complexContent>
			<xs:extension base="langstringBag"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="vocabIdentifierType">
		<xs:simpleContent>
			<xs:extension base="identifierType">
				<xs:attribute name="isRegistered" type="xs:boolean" default="false"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="termRefType">
		<xs:simpleContent>
			<xs:extension base="identifierType">
				<xs:attribute name="vocabularyIdentifier" type="xs:anyURI"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="vdexProfilesType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="lax"/>
			<xs:enumeration value="hierarchicalTokenTerms"/>
			<xs:enumeration value="flatTokenTerms"/>
			<xs:enumeration value="glossaryOrDictionary"/>
			<xs:enumeration value="thesaurus"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== NCEAS/morpho/lib/KNBRegistry.xml
<?xml version="1.0" encoding="UTF-8"?>

<vdex:vdex
	language="EN" 
	orderSignificant="false"
	profileType="hierarchicalTokenTerms"
	xmlns:vdex="http://www.imsglobal.org/xsd/imsvdex_v1p0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.imsglobal.org/xsd/imsvdex_v1p0 imsvdex_v1p0.xsd ">
		
	<vdex:vocabName>
		<vdex:langstring language="EN">KNBRegistryList</vdex:langstring>
	</vdex:vocabName>
	<vdex:vocabIdentifier isRegistered="false">http://knb.ecoinformatics.org/KNBRegistryList</vdex:vocabIdentifier>
	
	<!-- NCEAS -->
	<vdex:term orderSignificant="false" validIndex="true">
		<vdex:termIdentifier>National Center for Ecological Analysis and Synthesis</vdex:termIdentifier>
	</vdex:term>
	
	<!-- SNAP top level -->
	<vdex:term orderSignificant="false" validIndex="true">
		<vdex:termIdentifier>Science and Nature for People (SNAP)</vdex:termIdentifier>
		<vdex:caption>
			<vdex:langstring language="EN">SNAP</vdex:langstring>
		</vdex:caption>
		<vdex:description>
			<vdex:langstring language="EN">All SNAP working groups</vdex:langstring>
		</vdex:description>
		<vdex:metadata />

		<!-- working groups under SNAP -->
		<vdex:term><vdex:termIdentifier>Coastal Defenses</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Western Amazonia</vdex:termIdentifier></vdex:term>
		
	</vdex:term>	
		
	<!-- SANParks top level -->
	<vdex:term orderSignificant="false" validIndex="true">
		<vdex:termIdentifier>SANParks, South Africa</vdex:termIdentifier>
		<vdex:caption>
			<vdex:langstring language="EN">SANParks</vdex:langstring>
		</vdex:caption>
		<vdex:description>
			<vdex:langstring language="EN">Encompasses all SANParks</vdex:langstring>
		</vdex:description>
		<vdex:metadata />

		<!-- parks under SANParks container -->
		<vdex:term><vdex:termIdentifier>Addo Elephant National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Agulhas National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Augrabies Falls National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Bontebok National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Camdeboo National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Golden Gate Highlands National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Karoo National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Kgalagadi Transfrontier Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Knysna National Lake Area, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Kruger National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Mapungubwe National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Marakele National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Mokala National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Mountain Zebra National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Namaqua National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Table Mountain National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Tankwa Karoo National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Tsitsikamma National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>West Coast National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Wilderness National Park, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Ai-|Ais/Richtersveld Transfrontier National Park, South Africa</vdex:termIdentifier></vdex:term>
		
	</vdex:term>

	<!-- SAEON container -->
	<vdex:term orderSignificant="false" validIndex="true">
		<vdex:termIdentifier>SAEON, South Africa</vdex:termIdentifier>
		<vdex:caption>
			<vdex:langstring language="EN">SAEON</vdex:langstring>
		</vdex:caption>
		<vdex:description>
			<vdex:langstring language="EN">SAEON, South Africa</vdex:langstring>
		</vdex:description>
		<vdex:metadata />
		<vdex:term><vdex:termIdentifier>Elwandle SAEON Node, South Africa</vdex:termIdentifier></vdex:term>
		<vdex:term><vdex:termIdentifier>Ndlovu SAEON Node, South Africa</vdex:termIdentifier></vdex:term>
	</vdex:term>
	
</vdex:vdex>
